# Generated by Django 5.0.4 on 2024-05-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0035_deliveryperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('money_collected', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
