# Generated by Django 5.0.3 on 2024-05-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0037_healthcondition_product2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product2',
            name='description',
            field=models.TextField(default='good'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product2',
            name='image_url',
            field=models.URLField(default='www.xyz.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product2',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
