# Generated by Django 5.0.3 on 2024-05-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0038_product2_description_product2_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='password',
            field=models.CharField(default='12345', max_length=128),
            preserve_default=False,
        ),
    ]
