# Generated by Django 5.0.3 on 2024-05-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0039_deliveryperson_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customeremail',
            field=models.CharField(default='example@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
