# Generated by Django 5.0.3 on 2024-05-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossapp', '0040_orders_customeremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='customeremail',
            field=models.CharField(default='example@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
